---
- hosts: galera_server
  roles:
    - { role: galera_security, tags: [ 'setup' ] }
    - { role: galera_repos, tags: [ 'setup', 'packages' ] }
    - { role: galera_packages, tags: [ 'setup', 'packages' ] }
    - { role: galera_privs, tags: [ 'auth' ] }
    - { role: galera_conf, tags: [ 'config' ] }
