---
- hosts: galera_client 
  roles:
    - { role: galera_security, tags: [ 'setup' ] }
    - { role: galera_repos, tags: [ 'setup', 'packages' ] }
    - { role: galera_packages, tags: [ 'setup', 'packages' ] }
