- name: Ensure Apache is installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ httpd_packages }}"
  tags: httpd

- name: Install main configuration file
  template:
    src: httpd.conf.j2
    dest: "{{ httpd_config }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  tags: httpd

- name: Install status configuration file
  template:
    src: etc_httpd_conf.d_status.conf.j2
    dest: "{{ httpd_status_config }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  tags: httpd
  when: httpd_status_enable

- name: Install index.html
  template:
    src: index.html.j2
    dest: "{{ httpd_index_html }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  tags: httpd

- name: Install certificate files
  include_tasks: certificates.yml
  tags: httpd

- name: Install mod_ssl configuration file
  template:
    src: ssl.conf.j2
    dest: "{{ httpd_ssl_config }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  tags: httpd

- name: Ensure Apache is always running
  service:
    name: httpd
    state: started
    enabled: true
  tags: httpd 

- name: Ensure firewalld is disabled
  systemd: 
    name=firewalld 
    enabled=no
    state=stopped
  tags: httpd
